// User Model with Authentication & Authorization
// Demonstrates: HASHING (bcrypt with salt), AUTHENTICATION, AUTHORIZATION

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const userSchema = new mongoose.Schema({
  // Basic Information
  name: {
    type: String,
    required: true,
    trim: true
  },
  email: {
    type: String,
    required: true,
    unique: true,
    lowercase: true,
    trim: true
  },
  
  // HASHING DEMONSTRATION: Password stored as bcrypt hash with salt
  // Salt rounds = 10 (NIST recommendation for security vs performance)
  password: {
    type: String,
    required: true,
    minlength: 6
  },
  
  // AUTHORIZATION: Role-based Access Control
  // Three subjects as per lab requirements
  role: {
    type: String,
    enum: ['student', 'officer', 'admin'],
    default: 'student',
    required: true
  },
  
  // Multi-Factor Authentication (MFA)
  otp: {
    code: String,
    expiresAt: Date
  },
  
  isVerified: {
    type: Boolean,
    default: false
  },
  
  // Student-specific fields
  studentId: {
    type: String,
    sparse: true // Only for students
  },
  department: {
    type: String,
    sparse: true
  }
}, {
  timestamps: true
});

// ============================================
// PRE-SAVE HOOK: HASH PASSWORD WITH BCRYPT
// ============================================
// This demonstrates PASSWORD HASHING with SALT
// Salt is automatically generated by bcrypt (10 rounds)

userSchema.pre('save', async function(next) {
  // Only hash if password is modified or new
  if (!this.isModified('password')) {
    return next();
  }
  
  try {
    // Generate salt with 10 rounds (NIST recommended)
    // Salt prevents rainbow table attacks
    const salt = await bcrypt.genSalt(10);
    
    // Hash password with salt
    // Original password is NEVER stored in database
    this.password = await bcrypt.hash(this.password, salt);
    
    next();
  } catch (error) {
    next(error);
  }
});

// ============================================
// METHOD: COMPARE PASSWORD
// ============================================
// Used during login to verify password
// Demonstrates AUTHENTICATION process

userSchema.methods.comparePassword = async function(candidatePassword) {
  try {
    // bcrypt.compare automatically extracts salt from stored hash
    // and compares with candidate password
    return await bcrypt.compare(candidatePassword, this.password);
  } catch (error) {
    throw error;
  }
};

// ============================================
// METHOD: GENERATE OTP FOR MFA
// ============================================
// Demonstrates MULTI-FACTOR AUTHENTICATION

userSchema.methods.generateOTP = function() {
  // Generate 6-digit OTP
  const otp = Math.floor(100000 + Math.random() * 900000).toString();
  
  // Set OTP with expiry time
  this.otp = {
    code: otp,
    expiresAt: new Date(Date.now() + parseInt(process.env.OTP_EXPIRY || 5) * 60000)
  };
  
  return otp;
};

// ============================================
// METHOD: VERIFY OTP
// ============================================

userSchema.methods.verifyOTP = function(candidateOTP) {
  // Check if OTP exists
  if (!this.otp || !this.otp.code) {
    return false;
  }
  
  // Check if OTP has expired
  if (new Date() > this.otp.expiresAt) {
    return false;
  }
  
  // Verify OTP matches
  return this.otp.code === candidateOTP;
};

// ============================================
// AUTHORIZATION HELPER: Check Permissions
// ============================================
// Access Control Matrix implementation

userSchema.methods.canUploadDocuments = function() {
  // Only students can upload documents
  return this.role === 'student';
};

userSchema.methods.canVerifyDocuments = function() {
  // Officers and admins can verify documents
  return this.role === 'officer' || this.role === 'admin';
};

userSchema.methods.canViewAllDocuments = function() {
  // Officers and admins can view all documents
  return this.role === 'officer' || this.role === 'admin';
};

module.exports = mongoose.model('User', userSchema);
